<center><img src="https://www.usergioarboleda.edu.co/wp-content/uploads/ultimatum/imagens/logo-mobile-UniversidadSergioArboleda.png">
<h1>Universidad Sergio Arboleda</h1>
<h3>Ciencias de la Computacion e IA
<h4>Machine Learning</h4>
<p><b>INTEGRANTES:</b></p>
<p>Daniel Alejandro Olarte Ávila</p>
<p>Michael Steven Pinzon Villanueva</p>
<p>28 de Abril 2023</p>
<p>Profesor: Camilo Rodriguez</p></center>

In [288]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier, LogisticRegression, SGDRegressor, LinearRegression
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import plotly.graph_objects as go

# DIABETES

In [289]:
dfDiabetes = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv')
dfDiabetes.head(30)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6      148             72             35        0  33.6   
1             1       85             66             29        0  26.6   
2             8      183             64              0        0  23.3   
3             1       89             66             23       94  28.1   
4             0      137             40             35      168  43.1   
5             5      116             74              0        0  25.6   
6             3       78             50             32       88  31.0   
7            10      115              0              0        0  35.3   
8             2      197             70             45      543  30.5   
9             8      125             96              0        0   0.0   
10            4      110             92              0        0  37.6   
11           10      168             74              0        0  38.0   
12           10      139             80              0        0  27.1   
13            1      189             60             23      846  30.1   
14            5      166             72             19      175  25.8   
15            7      100              0              0        0  30.0   
16            0      118             84             47      230  45.8   
17            7      107             74              0        0  29.6   
18            1      103             30             38       83  43.3   
19            1      115             70             30       96  34.6   
20            3      126             88             41      235  39.3   
21            8       99             84              0        0  35.4   
22            7      196             90              0        0  39.8   
23            9      119             80             35        0  29.0   
24           11      143             94             33      146  36.6   
25           10      125             70             26      115  31.1   
26            7      147             76              0        0  39.4   
27            1       97             66             15      140  23.2   
28           13      145             82             19      110  22.2   
29            5      117             92              0        0  34.1   

    DiabetesPedigreeFunction  Age  Outcome  
0                      0.627   50        1  
1                      0.351   31        0  
2                      0.672   32        1  
3                      0.167   21        0  
4                      2.288   33        1  
5                      0.201   30        0  
6                      0.248   26        1  
7                      0.134   29        0  
8                      0.158   53        1  
9                      0.232   54        1  
10                     0.191   30        0  
11                     0.537   34        1  
12                     1.441   57        0  
13                     0.398   59        1  
14                     0.587   51        1  
15                     0.484   32        1  
16                     0.551   31        1  
17                     0.254   31        1  
18                     0.183   33        0  
19                     0.529   32        1  
20                     0.704   27        0  
21                     0.388   50        0  
22                     0.451   41        1  
23                     0.263   29        1  
24                     0.254   51        1  
25                     0.205   41        1  
26                     0.257   43        1  
27                     0.487   22        0  
28                     0.245   57        0  
29                     0.337   38        0

In [290]:
dfDiabetes.iloc[:,-1].head(30)

0     1
1     0
2     1
3     0
4     1
5     0
6     1
7     0
8     1
9     1
10    0
11    1
12    0
13    1
14    1
15    1
16    1
17    1
18    0
19    1
20    0
21    0
22    1
23    1
24    1
25    1
26    1
27    0
28    0
29    0
Name: Outcome, dtype: int64

In [291]:
procesito = MinMaxScaler()
procesito.fit(dfDiabetes.iloc[:,:-1])
dfDiabetes.iloc[:,:-1] = procesito.transform(dfDiabetes.iloc[:,:-1])
dfDiabetes

Pregnancies   Glucose  BloodPressure  SkinThickness   Insulin       BMI  \
0       0.352941  0.743719       0.590164       0.353535  0.000000  0.500745   
1       0.058824  0.427136       0.540984       0.292929  0.000000  0.396423   
2       0.470588  0.919598       0.524590       0.000000  0.000000  0.347243   
3       0.058824  0.447236       0.540984       0.232323  0.111111  0.418778   
4       0.000000  0.688442       0.327869       0.353535  0.198582  0.642325   
..           ...       ...            ...            ...       ...       ...   
763     0.588235  0.507538       0.622951       0.484848  0.212766  0.490313   
764     0.117647  0.613065       0.573770       0.272727  0.000000  0.548435   
765     0.294118  0.608040       0.590164       0.232323  0.132388  0.390462   
766     0.058824  0.633166       0.491803       0.000000  0.000000  0.448584   
767     0.058824  0.467337       0.573770       0.313131  0.000000  0.453055   

     DiabetesPedigreeFunction       Age  Outcome  
0                    0.234415  0.483333        1  
1                    0.116567  0.166667        0  
2                    0.253629  0.183333        1  
3                    0.038002  0.000000        0  
4                    0.943638  0.200000        1  
..                        ...       ...      ...  
763                  0.039710  0.700000        0  
764                  0.111870  0.100000        0  
765                  0.071307  0.150000        0  
766                  0.115713  0.433333        1  
767                  0.101196  0.033333        0  

[768 rows x 9 columns]

In [292]:
X_Diabetes = dfDiabetes.iloc[:,:-1]
y_Diabetes = dfDiabetes.iloc[:,-1]

In [293]:
X_trainDiabetes, X_testDiabetes, y_trainDiabetes, y_testDiabetes = train_test_split(X_Diabetes, y_Diabetes, test_size=0.2, random_state=0)
y_testDiabetes

661    1
122    0
113    0
14     1
529    0
      ..
476    1
482    0
230    1
527    0
380    0
Name: Outcome, Length: 154, dtype: int64

## MANUAL

In [294]:
def cost_function(y, y_pred):
    n = len(y)
    cost = (1/(2*n))*np.sum((y_pred-y)**2)
    return cost

def predict(x, w, b):
    return np.dot(x, w) + b

def predict_proba(x, w, b):
    return 1/(1+np.exp(-predict(x, w, b)))
 
def get_gradient(x, y, y_proba, w, b):
    n = len(y)
    dw = (1/n)*np.dot(x.T, (y_proba-y))
    db = (1/n)*np.sum(y_proba-y)
    return dw, db

def update_params(w, b, dw, db, learning_rate):
    w = w - learning_rate*dw
    b = b - learning_rate*db
    return w, b

def reg_log(X_train, y_train, niter=100, learning_rate=0.1):
    w = np.zeros(X_train.shape[1])
    b = 0
    for i in range(niter):
        y_proba = predict_proba(X_train, w, b)
        dw, db = get_gradient(X_train, y_train, y_proba, w, b)
        w, b = update_params(w, b, dw, db, learning_rate)
        if i%100==0:
            print(f'Costo: {cost_function(y_train, y_proba)}')
    return w, b


In [295]:
#Calcular el acurracy en train y test sin funciones
w, b = reg_log(X_trainDiabetes, y_trainDiabetes)
y_pred_train = predict_proba(X_trainDiabetes, w, b)
y_pred_test = predict_proba(X_testDiabetes, w, b)
y_pred_train = np.where(y_pred_train>=0.5, 1, 0)
y_pred_test = np.where(y_pred_test>=0.5, 1, 0)
print(f'Accuracy train: {np.mean(y_pred_train==y_trainDiabetes)}')
print(f'Accuracy test: {np.mean(y_pred_test==y_testDiabetes)}')


Costo: 0.125
Accuracy train: 0.6400651465798045
Accuracy test: 0.6948051948051948


## SGD Classifier

In [296]:
#Hacer lo mismo con SGDClassifier
clf = SGDClassifier(loss='log_loss', max_iter=1000, random_state=42, eta0= 0.1)
clf.fit(X_trainDiabetes, y_trainDiabetes)
print(f'Accuracy train: {clf.score(X_trainDiabetes, y_trainDiabetes)}')
print(f'Accuracy test: {clf.score(X_testDiabetes, y_testDiabetes)}')


Accuracy train: 0.7703583061889251
Accuracy test: 0.8116883116883117


In [297]:
clf.intercept_, clf.coef_[0][:3]

(array([-8.74459062]), array([ 1.88939427,  7.1044263 , -1.57677729]))

## LOGISTIC REGRESSION

In [298]:
#Hacer lo mismo con LogisticRegression
clfLog = LogisticRegression()
clfLog.fit(X_trainDiabetes, y_trainDiabetes)
print(f'Accuracy train: {clfLog.score(X_trainDiabetes, y_trainDiabetes)}')
print(f'Accuracy test: {clfLog.score(X_testDiabetes, y_testDiabetes)}')

Accuracy train: 0.758957654723127
Accuracy test: 0.8181818181818182


## GRAFICAR

In [299]:
clfLog.coef_[0][:3], clfLog.intercept_

(array([ 1.14776577,  4.43914628, -0.7203582 ]), array([-5.25847548]))

In [320]:
w[:3], b

(array([40050.03358044, 10171.73245828, 64077.71004519]), 117927.45688530804)

In [300]:
clf.coef_[0][:3], clf.intercept_

(array([ 1.88939427,  7.1044263 , -1.57677729]), array([-8.74459062]))

In [301]:
dfDiabetes.iloc[:30,:3]


Pregnancies   Glucose  BloodPressure
0      0.352941  0.743719       0.590164
1      0.058824  0.427136       0.540984
2      0.470588  0.919598       0.524590
3      0.058824  0.447236       0.540984
4      0.000000  0.688442       0.327869
5      0.294118  0.582915       0.606557
6      0.176471  0.391960       0.409836
7      0.588235  0.577889       0.000000
8      0.117647  0.989950       0.573770
9      0.470588  0.628141       0.786885
10     0.235294  0.552764       0.754098
11     0.588235  0.844221       0.606557
12     0.588235  0.698492       0.655738
13     0.058824  0.949749       0.491803
14     0.294118  0.834171       0.590164
15     0.411765  0.502513       0.000000
16     0.000000  0.592965       0.688525
17     0.411765  0.537688       0.606557
18     0.058824  0.517588       0.245902
19     0.058824  0.577889       0.573770
20     0.176471  0.633166       0.721311
21     0.470588  0.497487       0.688525
22     0.411765  0.984925       0.737705
23     0.529412  0.597990       0.655738
24     0.647059  0.718593       0.770492
25     0.588235  0.628141       0.573770
26     0.411765  0.738693       0.622951
27     0.058824  0.487437       0.540984
28     0.764706  0.728643       0.672131
29     0.294118  0.587940       0.754098

In [302]:
x1 = np.linspace(0, 1, 10)
x2 = np.linspace(0, 1, 10)
x1, x2 = np.meshgrid(x1, x2)
(-clf.coef_[0][0]*x1 - clf.coef_[0][1]*x2 - clf.intercept_)/clf.coef_[0][2]

array([[-5.54586288, -5.41272252, -5.27958215, -5.14644179, -5.01330143,
        -4.88016107, -4.74702071, -4.61388035, -4.48073999, -4.34759963],
       [-5.04523371, -4.91209335, -4.77895299, -4.64581263, -4.51267227,
        -4.37953191, -4.24639155, -4.11325119, -3.98011083, -3.84697046],
       [-4.54460454, -4.41146418, -4.27832382, -4.14518346, -4.0120431 ,
        -3.87890274, -3.74576238, -3.61262202, -3.47948166, -3.3463413 ],
       [-4.04397538, -3.91083501, -3.77769465, -3.64455429, -3.51141393,
        -3.37827357, -3.24513321, -3.11199285, -2.97885249, -2.84571213],
       [-3.54334621, -3.41020585, -3.27706549, -3.14392513, -3.01078477,
        -2.87764441, -2.74450405, -2.61136368, -2.47822332, -2.34508296],
       [-3.04271704, -2.90957668, -2.77643632, -2.64329596, -2.5101556 ,
        -2.37701524, -2.24387488, -2.11073452, -1.97759416, -1.8444538 ],
       [-2.54208787, -2.40894751, -2.27580715, -2.14266679, -2.00952643,
        -1.87638607, -1.74324571, -1.61010535

In [303]:
-clf.intercept_/clf.coef_[0][2]

array([-5.54586288])

In [304]:
fig = go.Figure(data=[go.Scatter3d(
    x=X_trainDiabetes.iloc[:,0],
    y=X_trainDiabetes.iloc[:,1],
    z=X_trainDiabetes.iloc[:,2],
    mode='markers',
    marker=dict(
        size=12,
        color=y_trainDiabetes,   
        colorscale='Viridis',   
        opacity=0.8
    )
)])

fig.update_layout(scene = dict(
                    xaxis_title='Glucose',
                    yaxis_title='Pregnancies',
                    zaxis_title='BloodPressure'),
                    width=700,
                    margin=dict(r=20, b=10, l=10, t=10))

#hiperplano

x1 = np.linspace(0, 1, 10)
x2 = np.linspace(0, 1, 10)
x1, x2 = np.meshgrid(x1, x2)

#x1*coef0 + x2*coef1 + x3*coef2 + intercept = 0
# x3*coef2 = -x1*coef0 -x2*coef1 - intercept / coef2


x3 = (-clf.coef_[0][0]*x1 - clf.coef_[0][1]*x2 - clf.intercept_)/clf.coef_[0][2]

fig.add_trace(go.Surface(x=x1, y=x2, z=x3, opacity=0.5))


fig.show()

# CALIFORNIA

In [305]:
dfCaliforniaTrain = pd.read_csv('https://raw.githubusercontent.com/DanielOlarte-GitHub/DataSetsFamosos/main/california_housing_train.csv')
dfCaliforniaTest = pd.read_csv('https://raw.githubusercontent.com/DanielOlarte-GitHub/DataSetsFamosos/main/california_housing_test.csv')
dfCaliforniaTrain.shape, dfCaliforniaTest.shape

((17000, 9), (3000, 9))

In [306]:
dfCaliforniaTest.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0

In [307]:
X_dfCaliforniaTest = dfCaliforniaTest.iloc[:,:-1]
y_dfCaliforniaTest = dfCaliforniaTest.iloc[:,-1]
X_dfCaliforniaTrain = dfCaliforniaTrain.iloc[:,:-1]
y_dfCaliforniaTrain = dfCaliforniaTrain.iloc[:,-1]
y_dfCaliforniaTrain

0         66900.0
1         80100.0
2         85700.0
3         73400.0
4         65500.0
           ...   
16995    111400.0
16996     79000.0
16997    103600.0
16998     85800.0
16999     94600.0
Name: median_house_value, Length: 17000, dtype: float64

In [308]:
X_dfCaliforniaTest.head(2)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   

   population  households  median_income  
0      1537.0       606.0         6.6085  
1       809.0       277.0         3.5990

In [309]:
escaladitoCalifornia = MinMaxScaler()
escaladitoCalifornia.fit(X_dfCaliforniaTrain)
X_dfCaliforniaTrain = escaladitoCalifornia.transform(X_dfCaliforniaTrain)
X_dfCaliforniaTest = escaladitoCalifornia.transform(X_dfCaliforniaTest)

In [310]:
X_dfCaliforniaTest

array([[0.22908367, 0.51328374, 0.50980392, ..., 0.04299448, 0.09949022,
        0.42127695],
       [0.60258964, 0.18278427, 0.82352941, ..., 0.02259032, 0.04538727,
        0.21372809],
       [0.65139442, 0.13177471, 0.50980392, ..., 0.04150901, 0.08123664,
        0.36506393],
       ...,
       [0.46314741, 0.39957492, 0.17647059, ..., 0.01933911, 0.03601381,
        0.12341899],
       [0.72011952, 0.16578108, 0.76470588, ..., 0.00120519, 0.00213781,
        0.19109392],
       [0.47011952, 0.19978746, 0.80392157, ..., 0.02102077, 0.04259168,
        0.55591647]])

In [311]:
y_dfCaliforniaTest

0       344700.0
1       176500.0
2       270500.0
3       330000.0
4        81700.0
          ...   
2995    225000.0
2996    237200.0
2997     62000.0
2998    162500.0
2999    500001.0
Name: median_house_value, Length: 3000, dtype: float64

In [312]:

def cost_function(y, y_proba):
    y_proba = np.clip(y_proba, 1e-10, 1-1e-10) # evitar valores muy cercanos a 0 o 1
    cost = -np.mean(y*np.log(y_proba)+(1-y)*np.log(1-y_proba))
    return cost


def predict(X, w, b):
    return np.dot(X, w) + b

def get_gradient(X, y, y_proba, w, b):
    n = len(y)
    dw = (1/n)*np.dot(X.T, (y_proba-y))
    db = (1/n)*np.sum(y_proba-y)
    return dw, db

def update_params(w, b, dw, db, learning_rate= 0.1):
    w = w - learning_rate*dw
    b = b - learning_rate*db
    return w, b

def reg_log(X, y, niter=100, learning_rate=0.1):
    w = np.random.randn(X.shape[1])
    b = 0
    for i in range(niter):
        y_proba = predict(X, w, b)
        dw, db = get_gradient(X, y, y_proba, w, b)
        w, b = update_params(w, b, dw, db, learning_rate)
        if i%100==0:
            print(f'Costo: {cost_function(y, y_proba)}')
    return w, b


In [313]:
# Calcular mse en train y test. con las funciones
w, b = reg_log(X_dfCaliforniaTrain, y_dfCaliforniaTrain)
y_pred_train = predict(X_dfCaliforniaTrain, w, b)
y_pred_test = predict(X_dfCaliforniaTest, w, b)
print(f'MSE train: {mean_squared_error(y_dfCaliforniaTrain, y_pred_train, squared=False)}')
print(f'MSE test: {mean_squared_error(y_dfCaliforniaTest, y_pred_test, squared=False)}')


Costo: -4429212.465869961
MSE train: 104907.63125596325
MSE test: 102871.13978227256


## SGD Regressor

In [314]:
modeloCaliSGD = SGDRegressor()
modeloCaliSGD.fit(X_dfCaliforniaTrain, y_dfCaliforniaTrain)
y_pred_train = modeloCaliSGD.predict(X_dfCaliforniaTrain)
y_pred_test = modeloCaliSGD.predict(X_dfCaliforniaTest)
print(f'MSE train: {mean_squared_error(y_dfCaliforniaTrain, y_pred_train, squared=False)}')
print(f'MSE test: {mean_squared_error(y_dfCaliforniaTest, y_pred_test, squared=False)}')

MSE train: 71368.17220712772
MSE test: 71249.61568566915


## LINEAR REGRESSION

In [315]:
modeloCaliReg = LinearRegression()
modeloCaliReg.fit(X_dfCaliforniaTrain, y_dfCaliforniaTrain)
y_pred_train = modeloCaliReg.predict(X_dfCaliforniaTrain)
y_pred_test = modeloCaliReg.predict(X_dfCaliforniaTest)
print(f'MSE train: {mean_squared_error(y_dfCaliforniaTrain, y_pred_train, squared=False)}')
print(f'MSE test: {mean_squared_error(y_dfCaliforniaTest, y_pred_test, squared=False)}')

MSE train: 69458.78759326927
MSE test: 69765.36022216803


## GRAFICAR

In [316]:
modeloCaliSGD.coef_, modeloCaliSGD.intercept_

(array([-417631.70816681, -386198.23385088,   62639.86046263,
         -91125.17436852,  251779.05603984, -352284.03625908,
         127140.47943761,  565866.11751984]),
 array([356753.71587007]))

In [317]:
w,b

(array([ 40050.03358044,  10171.73245828,  64077.71004519,  17538.98242727,
         14862.06646616,   4306.11627693,  15451.2247673 , 122973.47398911]),
 117927.45688530804)

In [321]:
modeloCaliReg.coef_, modeloCaliReg.intercept_

(array([ -433121.95806617,  -403930.58376103,    58685.44155621,
         -317828.95977251,   758127.21007452, -1373240.89961211,
          276296.33152022,   587360.59262494]),
 368442.6378451415)

In [318]:
#graficar con longitud y latitud 2d

fig = go.Figure(data=[go.Scatter(
    x=X_dfCaliforniaTrain[:,0],
    y=X_dfCaliforniaTrain[:,1],
    mode='markers',
    marker=dict(
        
        size=12,
        color=y_dfCaliforniaTrain,
        colorscale='Viridis',
        opacity=0.8
    )
)])

fig.update_layout(
    xaxis_title='Longitude',
    yaxis_title='Latitude',
    width=700,
    margin=dict(r=20, b=10, l=10, t=10))

#recta de modeloCaliSGD solo para los 2 primeros coef
x1 = np.linspace(0, 1, 10)

x2 = (-modeloCaliSGD.coef_[0]*x1 - modeloCaliSGD.intercept_)/modeloCaliSGD.coef_[1]

fig.add_trace(go.Scatter(x=x1, y=x2, mode='lines', name='recta modeloCaliSGD'))





fig.show()

# CONCLUSION

*  En el caso de diabetes, el modelo que mejor se ajusta es el de SGD Classifier, ya que tiene un mejor score y un mejor tiempo de ejecución.

*  En el caso de california, el modelo que mejor se ajusta es el de SGD Regressor, ya que tiene un mejor score y un mejor tiempo de ejecución.

* En ambos casos, podemos presenciar que para el modelo que se realizo manualmente, el tiempo de ejecución es mucho mayor, y el score es menor, por lo que se puede concluir que los modelos de sklearn son mucho mas eficientes y precisos a no ser que se le aumente el numero de iteraciones de 100 a 1000  donde se puede ver mejores resultados casi similares a los de SGD o Logistic.


