In [7]:
from keras.layers import Dense
from keras.models import Sequential
import numpy as np
import pandas as pd

In [8]:
data = np.array([0.9, 0.2])
data

array([0.9, 0.2])

In [9]:
data.reshape(1, 2)

array([[0.9, 0.2]])

In [18]:
red = Sequential()
red.add(Dense(2, activation='relu', weights=[np.array([[0.4, 0.2], [0.9, 0.7]]), np.array([0.1, 1.3])]))
red.add(Dense(2, activation='relu', weights=[np.array([[0.3, 0.1], [0.2, 0.2]]), np.array([0.5, 0.1])]))
red.add(Dense(1, activation='sigmoid', weights=[np.array([[0.3], [0.7]]), np.array([0.5])]))

red.compile(optimizer='sgd', loss='entr', metrics=['accuracy'])
red.predict(data.reshape(1, 2))

1/1 [==============================] - 0s 182ms/step


array([[0.7588527]], dtype=float32)

In [15]:
data.reshape(1, 2)

array([[0.9, 0.2]])

In [16]:
data

array([0.9, 0.2])